name: CI
on:
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
    - run: |
        npm install
        npm i --no-save @wfcd/items@latest
        npm i --no-save warframe-worldstate-data@latest
        npm run lint
        npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        node-version:
         - 'lts/gallium'
         - 'lts/hydrogen'
         - 'lts/iron'
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test
      env:
        CI: true
      run: | 
        npm install
        npm i --no-save @wfcd/items@latest
        npm i --no-save warframe-worldstate-data@latest
        npm test
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - run: |
          npm install
          npm i --no-save @wfcd/items@latest
          npm i --no-save warframe-worldstate-data@latest
      - run: npm test
        env:
          CI: true
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
